"""initial

Revision ID: 5ee17ef4fb83
Revises: 
Create Date: 2026-05-10 23:45:33.308532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee17ef4fb83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('envios_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zona', sa.Enum('CABA', 'GBA_NORTE', 'GBA_SUR', 'GBA_OESTE', name='zonaenvio'), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zona')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=500), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=50), nullable=False),
    sa.Column('direccion_entrega', sa.String(length=500), nullable=False),
    sa.Column('tipo_entrega', sa.Enum('ENVIO', 'RETIRO', name='tipoentrega'), nullable=False),
    sa.Column('zona_envio', sa.Enum('CABA', 'GBA_NORTE', 'GBA_SUR', 'GBA_OESTE', name='zonaenvio'), nullable=True),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'ENTREGADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('EFECTIVO', 'TRANSFERENCIA', name='metodopago'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', name='estadopago'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_por_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_por_unidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_unidad', sa.Enum('KG', 'UNIDAD', name='tipounidad'), nullable=False),
    sa.Column('stock_kg', sa.Float(), nullable=True),
    sa.Column('stock_unidades', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sa.Enum('KG', 'UNIDAD', name='unidadmedida'), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_items')
    op.drop_table('imagenes')
    op.drop_table('productos')
    op.drop_table('pagos')
    op.drop_table('pedidos')
    op.drop_table('envios_config')
    op.drop_table('categorias')
    op.drop_table('admins')
    # ### end Alembic commands ###
