"""add gramos field to productos

Revision ID: 6d85258a3988
Revises: 5ee17ef4fb83
Create Date: 2026-05-11 13:35:23.407021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d85258a3988'
down_revision: Union[str, None] = '5ee17ef4fb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('gramos', sa.Integer(), server_default='1000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'gramos')
    # ### end Alembic commands ###
