"""add cliente_email to pedidos

Revision ID: ef2cc72dbacf
Revises: 6d85258a3988
Create Date: 2026-05-11 14:57:12.281023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2cc72dbacf'
down_revision: Union[str, None] = '6d85258a3988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cliente_email', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'cliente_email')
    # ### end Alembic commands ###
